### ISSUE TITLE
Replace `github.com/pkg/errors` dependency with native error wrapping

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/bom#114]
The PR https://github.com/kubernetes/release/pull/2478 got reverted because it caused troubles with the error wrapping conversion.

We should still do that, because the package `github.com/pkg/errors` is now in maintenance mode due to the golang native error wrapping. The goal is to do that on a package-by-package basis, where everyone is welcome to contribute.

#### The basic conversion rules:

- use the `errors` import in favor of `github.com/pkg/errors`
- convert `errors.Errorf` to `fmt.Errorf`
- convert `errors.Wrap(err, "…")` to `fmt.Errorf("…: %w", err)` and check that `err != nil` before
- convert `errors.Wrapf(err, "… %s: %s", foo, bar)` to `fmt.Errorf("… %s: %s: %w", foo, bar err)` and check that `err != nil` before

#### Packages to be converted:

- [x] pkg/spdx (@DiptoChakrabarty): #122
- [x] pkg/license (@DiptoChakrabarty): #120, #121
- [x] magefile.go (@ArkaSaha30): #115, #119
- [x] pkg/provenance (@ArkaSaha30): #115, #119
- [x] cmd/bom (@Priyankasaggu11929): #116
- [x] pkg/osinfo (@Priyankasaggu11929): #117
- [x] pkg/query (@Priyankasaggu11929): #118

**Comment by saschagrunert** [comment]
@palnabarun this could be another one

cc @Debanitrkl @Priyankasaggu11929 @jasonbraganza @DiptoChakrabarty @ArkaSaha30 @pradeepnnv

**Comment by Priyankasaggu11929** [comment]
I'll pick up:

- cmd/bom
- pkg/query
- pkg/osinfo

**Comment by DiptoChakrabarty** [comment]
Ill take 
- pkg/license
- pkg/spdx

**Comment by ArkaSaha30** [comment]
I'll take up 

- pkg/provenance
- magefile.go
