### ISSUE TITLE
Set-up k-sigs/bom release infra

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#35]
After some discussions with Carlos, we decided to start staging and promoting the artifacts of the kubernetes-sigs/bom project. This is the tracking issue to track the rollout.

### Tasks
- [x] Request staging project + bom bucket - https://github.com/kubernetes/k8s.io/pull/3319
- [ ] Create presubmits in kubernetes/test-infra
- [ ] Write cloud build job

/cc @cpanato
